---
title: "projects"
format: html
editor: visual
---
# Robert's Ranch

In the fall of 2024, I led groups of students to Robert's Ranch in Livermore Colorado, where we used forensic botany to assess wetland plant occurrence. 1.navigation to 4WD roads on Robert's Ranch 2. map creation with ArcGIS Pro and Avenza 3. I consulted the NRCS web soil survey to compare soil conditions with wetland establishment success 4. synthesis of past monitoring analyses, which had varying focuses, to clarify monitoring objectives for future groups

## [North Shields Ponds Weed Management Plan] <https://docs.google.com/document/d/1AX4zkwBYXkeCqfemrGFTAjwd_TGqb6Y0MdJuemKOkNo/edit?usp=sharing)>

In 2024, I also consulted with local land managers about ecosystem management in a semi-urban habitat, North Shields Ponds, creating an integrated weed management plan based on their priorities and exploring mechanical, chemical, and cultural weed management options to improve wildlife habitat.

1.  Using ArcGIS FieldMaps to create weed management zone polygons
2.  map creation in ArcGIS pro phone interviews with local land managers
3.  analyzing species occurrence for wildlife habitat to prioritize weed managment zones

## [Independent Study: Forest Floor] (<https://docs.google.com/document/d/1HW5zR6KkieMTj4rjqezmoprqn73cZZBaaE85sHoD4eQ/edit?usp=sharing)> Macroinvertebrates of the Chakra Agroecosytem

In autumn of 2023, I conducted an independent study assessing macroinvertebrate diversity beneath cacao trees in eastern Ecuador, where the region's agroforestry provides a shining example of urban ecological integration.
